export enum KeyboardEvnet {
  Enter = "ENTER",
  Backspace = "BACKSPACE",
  ArrowLeft = "ARROWLEFT",
  ArrowUp = "ARROWUP",
  ArrowRight = "ARROWRIGHT",
  ArrowDown = "ARROWDOWN",
  Heading1 = "CTRL+1",
  Heading2 = "CTRL+2",
  Heading3 = "CTRL+3",
  Heading4 = "CTRL+4",
  Heading5 = "CTRL+5",
  Heading6 = "CTRL+6",
  Bold = "CTRL+B",
  Italic = "CTRL+I",
  Blockquote = "CTRL+SHIFT+Q",
}
